allow custom func_name label
shanbay/cachext pull request #17
Opened 2022-07-13 06:16 UTC by gezishu

2022-07-13 06:58 UTC, fenngwd requested changes

2022-07-13 06:58 UTC, fenngwd commented on cachext/cache.py
> +            labels = (self.client.prefix, build_func_name_label(f))
How to make a custom label if this function is not dynamic?

2022-07-14 02:28 UTC, fenngwd commented on cachext/exts.py
> +        monitor_label_builder = opts.pop('monitor_label_builder', None)
建议参考cache_key的实现方式，将label_builder作为cahed的参数传入

2022-07-14 02:31 UTC, fenngwd commented on cachext/exts.py
> +        monitor_label_builder = opts.pop('monitor_label_builder', None)
建议不要整体全部自定义，之前已有Label需要默认保留，提供增加标签的方式。

2022-07-14 05:04 UTC, gezishu commented on cachext/exts.py
> +        monitor_label_builder = opts.pop('monitor_label_builder', None)
> 建议不要整体全部自定义，之前已有Label需要默认保留，提供增加标签的方式。

保留了默认标签的生成方式

2022-07-19 06:26 UTC, fenngwd commented
/LGTM

2022-07-20 09:52 UTC, fenngwd approved these changes

2022-07-20 09:52 UTC, merged